INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Marszałkowska 5', 'mpastuszka@gmail.com', CURRENT_TIMESTAMP, null, 5, 'Pastuszka', 12, '+48 555 543 123');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Aia 34', 'nali@gmail.com', CURRENT_TIMESTAMP, null, 5, 'Kask', 3, '+372 7564784');


INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Muru 3', 'jeeeea@gmail.com', CURRENT_TIMESTAMP, null, 5, 'Juminda', 12, '+433333 123');